### ISSUE TITLE
Make hpgltools installable via devtools::install_github(), etc.

### ISSUE THREAD

**Issue by khughitt** [elsayed-lab/hpgltools#83]
If possible, it would be useful to modify the package dependencies so that hpgltools can be installed by methods that can work with github-hosted packages (`devtools::install_github()`, `pak::pkg_install()`, `renv::install()`, etc.)

Aside from the convenience factor, a big advantage of this is that hpgltools could then be included in an [renv lockfiles](https://rstudio.github.io/renv/reference/lockfile.html), along with a an associated git commit hash.

In order to get `install_github()` to work, these are the packages I had to install first:

- GenomicFeatures
- packrat
- sva
- variancePartition
- clusterProfiler

**Comment by abelew** [comment]
hmm I have been doing this off my makefile for so long I had forgotten the poorly written description.

In order to replicate your behavior, I set the R_ variables to a temporary directory.  Fired up R with this blank path, installed devtools, and invoked install_github("abelew/hpgltools")

It spent some time installing prerequisites, I am guessing from the Imports: field of the DESCRIPTION.   As I recall, it does not work well if I move most of the Suggests: field entries to Imports: from the perspective of R CMD check; which is strange because most of them are required for the various tests.

In any event, it eventually finished installing a bunch of packages and as expected I got the same errors.  I moved GenomicFeatures to Imports: and got the expected new installations.  I will move one package/commit until it installs happily and then do the r cmd check to see how it went...

oooo I get it, this is due to the fact that I used YiHui's workaround for ::: in 01_hpgltools.r...  Interesting.

With those changes, it installed for me via install_github().  I am still a bit concerned that most of the material in Suggests: is basically required for most fun things to work.

**Comment by khughitt** [comment]
Thanks, Trey!

If there are  a few "suggested" packages that are used often, you could perhaps just moved them to depends..

otherwise (I think you may already do this...) you can perhaps just print a message and guide / prompt the user to install other dependencies on-the-fly, as they are needed?

**Comment by abelew** [comment]
True on both accounts.  Perhaps I should reconsider some of this though; but I have been using my Makefile to ensure that there are no problems for so long I had forgotten that there are other install scenarios.  There are advantages and disadvantages for each choice and I am not sure which is best, so I think unless you have a specific desire I will leave it as is.
